//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Bookrequest')
export class BookrequestEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  user_id: number;

  @Column('integer', { nullable: true })
  book_id: number;

  @Column('date', { nullable: true })
  request_date: Date;

  @Column('date', { nullable: true })
  issue_date: Date;

  @Column('date', { nullable: true })
  return_date: Date;

  @Column('text', { nullable: true })
  status: string;
}
