//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Book')
export class BookEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  content: string;

  @Column('text', { nullable: true })
  author: string;

  @Column('integer', { nullable: true })
  section_id: number;

  @Column('date', { nullable: true })
  date_issued: Date;

  @Column('date', { nullable: true })
  return_date: Date;

  @Column('text', { nullable: true })
  language: string;

  @Column('integer', { nullable: true })
  number_of_pages: number;

  @Column('date', { nullable: true })
  created_at: Date;
}
