//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Feedback')
export class FeedbackEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  user_id: number;

  @Column('integer', { nullable: true })
  book_id: number;

  @Column('integer', { nullable: true })
  rating: number;

  @Column('text', { nullable: true })
  comment: string;

  @Column('date', { nullable: true })
  created_at: Date;
}
