//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UserEntity } from './db/User.entity';
import { SectionEntity } from './db/Section.entity';
import { BookEntity } from './db/Book.entity';
import { BookrequestEntity } from './db/Bookrequest.entity';
import { FeedbackEntity } from './db/Feedback.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UserEntity,
      SectionEntity,
      BookEntity,
      BookrequestEntity,
      FeedbackEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      User: [
        {
          id: 1,
          name: 'Alice Johnson',
          email: 'alice.johnson@example.com',
          password: 'A1ic3J0hn$on!',
          role: 'Librarian',
          registration_date: '2023-12-01T09:15:00',
        },
        {
          id: 2,
          name: 'Bob Smith',
          email: 'bob.smith@example.com',
          password: 'B0bSm1th#2023',
          role: 'Student',
          registration_date: '2024-01-10T14:22:00',
        },
        {
          id: 3,
          name: 'Clara Lee',
          email: 'clara.lee@example.com',
          password: 'Cl@raL33!lib',
          role: 'Student',
          registration_date: '2024-02-05T11:45:00',
        },
        {
          id: 4,
          name: 'David Patel',
          email: 'david.patel@example.com',
          password: 'Dav1dP@t3l*',
          role: 'Student',
          registration_date: '2024-03-12T08:30:00',
        },
        {
          id: 5,
          name: 'Emma Williams',
          email: 'emma.williams@example.com',
          password: 'Emm@W1ll!ams',
          role: 'Librarian',
          registration_date: '2023-12-15T16:05:00',
        },
      ],
      Section: [
        {
          id: 1,
          name: 'Science Fiction',
          date_created: '2023-09-15T10:30:00',
          description:
            'A section dedicated to futuristic and imaginative literature, exploring advanced science and technology.',
        },
        {
          id: 2,
          name: 'History',
          date_created: '2023-10-01T14:45:00',
          description:
            'Books and resources covering historical events, biographies, and ancient civilizations.',
        },
        {
          id: 3,
          name: 'Literature',
          date_created: '2023-11-20T09:15:00',
          description:
            'Classic and modern works of prose, poetry, and drama from around the world.',
        },
        {
          id: 4,
          name: 'Technology',
          date_created: '2024-01-05T16:00:00',
          description:
            'Resources on computing, engineering, and the latest technological advancements.',
        },
        {
          id: 5,
          name: 'Languages',
          date_created: '2024-02-12T11:20:00',
          description:
            'A collection of books and materials for learning and mastering different languages.',
        },
      ],
      Book: [
        {
          id: 1,
          name: 'Introduction to Algorithms',
          content:
            'This comprehensive book covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers.',
          author: 'Thomas H. Cormen',
          section_id: 2,
          date_issued: '2024-06-01T10:00:00',
          return_date: '2024-06-15T10:00:00',
          language: 'English',
          number_of_pages: 1312,
          created_at: '2024-05-25T09:30:00',
        },
        {
          id: 2,
          name: 'Pride and Prejudice',
          content:
            'A classic novel of manners that explores the concerns and difficulties of genteel women living in early 19th-century England.',
          author: 'Jane Austen',
          section_id: 1,
          date_issued: '2024-06-03T14:20:00',
          return_date: '2024-06-17T14:20:00',
          language: 'English',
          number_of_pages: 432,
          created_at: '2024-05-28T11:00:00',
        },
        {
          id: 3,
          name: 'Cien años de soledad',
          content:
            'La obra narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo.',
          author: 'Gabriel García Márquez',
          section_id: 3,
          date_issued: '2024-06-05T09:00:00',
          return_date: '2024-06-19T09:00:00',
          language: 'Spanish',
          number_of_pages: 496,
          created_at: '2024-05-30T13:45:00',
        },
        {
          id: 4,
          name: 'Le Petit Prince',
          content:
            "Un conte poétique et philosophique sous l'apparence d'un conte pour enfants, qui aborde des thèmes profonds sur la vie et l'amitié.",
          author: 'Antoine de Saint-Exupéry',
          section_id: 4,
          date_issued: '2024-06-07T12:10:00',
          return_date: '2024-06-21T12:10:00',
          language: 'French',
          number_of_pages: 96,
          created_at: '2024-06-01T10:00:00',
        },
        {
          id: 5,
          name: 'Python Programming: An Introduction to Computer Science',
          content:
            'This book is designed to be used as the primary textbook in a college-level first course in computing.',
          author: 'John Zelle',
          section_id: 5,
          date_issued: '2024-06-09T16:30:00',
          return_date: '2024-06-23T16:30:00',
          language: 'English',
          number_of_pages: 552,
          created_at: '2024-06-02T15:20:00',
        },
      ],
      Bookrequest: [
        {
          id: 1,
          user_id: 2,
          book_id: 3,
          request_date: '2024-06-01T10:15:00',
          issue_date: '2024-06-01T11:00:00',
          return_date: '2024-06-15T11:00:00',
          status: 'issued',
        },
        {
          id: 2,
          user_id: 1,
          book_id: 5,
          request_date: '2024-06-03T09:30:00',
          issue_date: '2024-06-03T10:00:00',
          return_date: '2024-06-17T10:00:00',
          status: 'issued',
        },
        {
          id: 3,
          user_id: 3,
          book_id: 2,
          request_date: '2024-06-05T14:45:00',
          issue_date: '2024-06-05T15:00:00',
          return_date: '2024-06-19T15:00:00',
          status: 'returned',
        },
        {
          id: 4,
          user_id: 4,
          book_id: 1,
          request_date: '2024-06-07T08:20:00',
          issue_date: '2024-06-07T09:00:00',
          return_date: '2024-06-21T09:00:00',
          status: 'expired',
        },
        {
          id: 5,
          user_id: 5,
          book_id: 4,
          request_date: '2024-06-09T16:10:00',
          issue_date: '2024-06-09T17:00:00',
          return_date: '2024-06-23T17:00:00',
          status: 'requested',
        },
      ],
      Feedback: [
        {
          id: 1,
          user_id: 2,
          book_id: 3,
          rating: 5,
          comment:
            'An excellent read! The content was well-organized and very informative.',
          created_at: '2024-06-10T14:23:45',
        },
        {
          id: 2,
          user_id: 4,
          book_id: 1,
          rating: 4,
          comment:
            'Great book, but I wish there were more examples in the later chapters.',
          created_at: '2024-06-09T09:15:30',
        },
        {
          id: 3,
          user_id: 1,
          book_id: 5,
          rating: 3,
          comment:
            'The book was decent, but some sections were a bit hard to follow.',
          created_at: '2024-06-08T18:42:10',
        },
        {
          id: 4,
          user_id: 3,
          book_id: 2,
          rating: 2,
          comment: 'I found the content outdated and not very engaging.',
          created_at: '2024-06-07T11:05:55',
        },
        {
          id: 5,
          user_id: 5,
          book_id: 4,
          rating: 4,
          comment: 'Good book overall. The author explains concepts clearly.',
          created_at: '2024-06-06T16:37:20',
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UserEntity', data.User);
      await this.SeedResource('SectionEntity', data.Section);
      await this.SeedResource('BookEntity', data.Book);
      await this.SeedResource('BookrequestEntity', data.Bookrequest);
      await this.SeedResource('FeedbackEntity', data.Feedback);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
