//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { UserList, UserCreate, UserEdit } from './resources/User';
import { SectionList, SectionCreate, SectionEdit } from './resources/Section';
import { BookList, BookCreate, BookEdit } from './resources/Book';
import {
  BookrequestList,
  BookrequestCreate,
  BookrequestEdit,
} from './resources/Bookrequest';
import {
  FeedbackList,
  FeedbackCreate,
  FeedbackEdit,
} from './resources/Feedback';
import UserIcon from '@mui/icons-material/Person';
import SectionIcon from '@mui/icons-material/Category';
import BookIcon from '@mui/icons-material/MenuBook';
import BookrequestIcon from '@mui/icons-material/AssignmentReturn';
import FeedbackIcon from '@mui/icons-material/RateReview';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/aa712379f">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="User"
          options={{ label: 'User' }}
          list={UserList}
          create={UserCreate}
          edit={UserEdit}
          recordRepresentation="name"
          icon={UserIcon}
        />
        <Resource
          name="Section"
          options={{ label: 'Section' }}
          list={SectionList}
          create={SectionCreate}
          edit={SectionEdit}
          recordRepresentation="name"
          icon={SectionIcon}
        />
        <Resource
          name="Book"
          options={{ label: 'Book' }}
          list={BookList}
          create={BookCreate}
          edit={BookEdit}
          recordRepresentation="name"
          icon={BookIcon}
        />
        <Resource
          name="Bookrequest"
          options={{ label: 'Book Request' }}
          list={BookrequestList}
          create={BookrequestCreate}
          edit={BookrequestEdit}
          recordRepresentation="id"
          icon={BookrequestIcon}
        />
        <Resource
          name="Feedback"
          options={{ label: 'Feedback' }}
          list={FeedbackList}
          create={FeedbackCreate}
          edit={FeedbackEdit}
          recordRepresentation="id"
          icon={FeedbackIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
